### ISSUE TITLE
Install button not working

### ISSUE THREAD

**Issue by kothavade** [urwrstkn8mare/gog-riot-integration#14]
When you press the install button for a riot game you don't have installed, it says "Please wait, we are launching Riot" and then nothing happens.

Maybe make it so that pressing the button opens the download page for the respective games?

Log attached.

[plugin-riot-b4c0c2f5-23dc-4326-aa65-e9fabef61a3b.log](https://github.com/urwrstkn8mare/galaxy-riot-integration/files/5791818/plugin-riot-b4c0c2f5-23dc-4326-aa65-e9fabef61a3b.log)

**Comment by kothavade** [comment]
2021-01-09 15:57:01,728 - galaxy.api.jsonrpc - INFO - Handling notification: method=install_game, params={'game_id': 'league_of_legends'}
2021-01-09 15:57:01,728 - galaxy.task_manager - DEBUG - Task manager jsonrpc server: creating task 6 (install_game)
2021-01-09 15:57:01,729 - galaxy.task_manager - DEBUG - Task manager plugin external: creating task 30 (install_game)
2021-01-09 15:57:01,729 - plugin - INFO - Installing game
2021-01-09 15:57:01,732 - utils.misc - INFO - Opening: C:\Riot Games\Riot Client\RiotClientServices.exe
With args: ['--launch-product=league_of_legends', '--launch-patchline=live']
2021-01-09 15:57:01,732 - utils.misc - INFO - Running: "C:\Riot Games\Riot Client\RiotClientServices.exe" --launch-product=league_of_legends --launch-patchline=live
2021-01-09 15:57:01,743 - galaxy.task_manager - ERROR - Task manager jsonrpc server: exception raised in task 6 (install_game)
Traceback (most recent call last):
  File "C:\Users\kotha\AppData\Local\GOG.com\Galaxy\plugins\installed\windows-v0.2.4-galaxy-riot-integration\galaxy\task_manager.py", line 21, in task_wrapper
    result = await coro
  File "C:\Users\kotha\AppData\Local\GOG.com\Galaxy\plugins\installed\windows-v0.2.4-galaxy-riot-integration\galaxy\api\plugin.py", line 264, in wrapper
    return await self._external_task_manager.create_task(handler(*args, **kwargs), name, False)
  File "C:\Users\kotha\AppData\Local\GOG.com\Galaxy\plugins\installed\windows-v0.2.4-galaxy-riot-integration\galaxy\task_manager.py", line 21, in task_wrapper
    result = await coro
  File "C:\Users\kotha\AppData\Local\GOG.com\Galaxy\plugins\installed\windows-v0.2.4-galaxy-riot-integration\plugin.py", line 110, in install_game
    self.local_client.launch(game_id, save_process=False)
  File "C:\Users\kotha\AppData\Local\GOG.com\Galaxy\plugins\installed\windows-v0.2.4-galaxy-riot-integration\local.py", line 32, in launch
    [f"--launch-product={game_id}", "--launch-patchline=live"],
  File "C:\Users\kotha\AppData\Local\GOG.com\Galaxy\plugins\installed\windows-v0.2.4-galaxy-riot-integration\utils\misc.py", line 42, in open_path
    return run(cmd)
  File "C:\Users\kotha\AppData\Local\GOG.com\Galaxy\plugins\installed\windows-v0.2.4-galaxy-riot-integration\utils\misc.py", line 36, in run
    return subprocess.Popen(cmd, shell=shell)
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\subprocess.py", line 775, in __init__
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\subprocess.py", line 1178, in _execute_child
OSError: [WinError 740] The requested operation requires elevation

This seems to be the relevant part, if that helps.

**Comment by urwrstkn8mare** [comment]
Hi @vedkothavade, thanks for reporting this and for the snippet from the logs. I think it has something to do with administrator permissions. Just to confirm, when you click install, there is no popup anywhere on the computer asking for permission of any sort? It may not popup but be a flashing yellow tab on the Windows taskbar.

**Comment by kothavade** [comment]
Nope, nothing happens at all except for that popup I mentioned, even in the taskbar. I tried running Galaxy as an administrator and that didn't change anything either.
